spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_mars_edu?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true