spring:
  datasource:
    url: jdbc:mysql://47.97.183.139:3306/db_mars_edu?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: chris
    password: Gk!123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true